### PR TITLE
Navigation tests and CI change

### PR DESCRIPTION
**Pull request by Adrianmeda**
⛓ **Description:**

- Helps #122 (issue)

Split up the tests to smaller ones to identify which one is not working in the CI.
Changed our workflow android-ci build with input from @Quinstedt

🛠 **Type of change:**

- [x] Split up the tests
- [x] Adjusted android-ci

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by Quinstedt** [comment]
@platisd
Hi, could you please delete those test ? That are stuck.
image

**Comment by Quinstedt** [comment]
@platisd is there anything we can do to delete the previous CI?

**Comment by platisd** [comment]
I've updated the branch protection rules to the new job names you are using (the easiest solution would have been to use the same ones as before :stuck_out_tongue:). Please ping on Slack if you need my action, I get heavily spammed by PR emails so I may easily miss them.

**Comment by Quinstedt** [comment]
Oh I see, thank you for the response :)

**Comment by Quinstedt** [comment]
@Adrianmeda @Toerngren @umairngo  you are good to go, you can close this pull request now

**Review by gusandchbh — APPROVED** [review]
Great job!

**Pull request merged**
